server:
  port: 9966
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: rocketmq-reput
  servlet:
    multipart:
      max-request-size: 600MB
      max-file-size: 600MB

logging:
  home: "."

# rocketmq reput config
rocketmq:
  reput:
    # 启动模式：三个选项：CLIENT,SERVER,MIXED(CLIENT+SERVER)
    startMode: SERVER
    client:
      serverAddr: 'http://localhost:9966'
      commitlog:
        node0: '/Users/xuxd/DemoCode/java/daily-demo/rocketmq-demo/rmq-home/zip'
      # 扫描间隔，单位分钟
      scanInterval: 1
      # 过滤文件大小，MB
      fileFilterSize: 950
      # 过期时间，单位小时
      expireTime: 48
    server:
      fileReservedTime: 24
      deleteWhen: 04
      enableDledger: false
      rootDir: ${user.dir}/rmq_home
      store:
        node0: '${rocketmq.reput.server.rootDir}/node0'
